package com.example.trivialapp_base.model

// Definición de la clase de datos Pregunta según requisitos
data class Pregunta(
    val pregunta: String,
    val categoria: String,
    val dificultad: String, // "Facil", "Medio", "Dificil"
    val respuesta1: String,
    val respuesta2: String,
    val respuesta3: String,
    val respuesta4: String,
    val respuestaCorrecta: String // Debe coincidir con una de las anteriores
)

// Objeto para simular la base de datos local (Hardcoded)
object ProveedorPreguntas {
    fun obtenerPreguntas(): MutableList<Pregunta> {
        return mutableListOf(
            Pregunta("¿Cuántos PP como máximo puede tener Hiperrayo?", "Movimientos", "Facil", "5", "16", "8", "10", "8"),
            Pregunta("¿Cuánta potencia base tiene erupción?", "Movimientos", "Facil", "100", "120", "150", "200", "150"),
            Pregunta("¿Qué pokemon no tiene debilidades en la práctica?", "Tabla de Tipos", "Medio", "Rotom Ventilador", "Zoroark de Hisui", "Eelektross", "Spiritomb", "Eelektross"),
            Pregunta("¿Cuánto aumentan la potencia de los movimientos de su tipo los campos psíquico, eléctrico y de hierba?", "Movimientos", "Medio", "Un 10%", "Un 30%", "Un 50%", "Un 25%", "Un 30%"),
            Pregunta("¿Qué hace el tera estelar?", "Generaciones", "Dificil", "Potencia un movimiento de cada tipo una vez", "Cambia el tipo defensivo", "Hace que teraexplosión siempre haga supereficaz", "Potencia solo los movimientos de tipo estelar", "Potencia un movimiento de cada tipo una vez"),
            Pregunta("¿Qué grupo de pokemon no estaba en espada y escudo?", "Generaciones", "Medio", "Los Regi", "Los Ultraentes", "Arceus y Darkrai", "Los Iniciales de Séptima Generación", "Arceus y Darkrai"),
            Pregunta("¿Qué pokemon de tipo bicho es el único que ha ganado el mundial?", "VGC", "Dificil", "Accelgor", "Volcarona", "Escavalier", "Scizor", "Escavalier"),
            Pregunta("¿Cuál de estos pokemon no tiene la habilidad intimidación?", "Características", "Facil", "Incineroar", "Haxorus", "Luxray", "Mawile", "Haxorus"),
            Pregunta("¿Cuál de estos pokemon no ha ganado ningún torneo oficial de VGC?", "VGC", "Medio", "Clefairy", "Eevee", "Pikachu", "Cottonee", "Pikachu"),
            Pregunta("¿Cuál de estos pokemon no evoluciona?", "Características", "Medio", "Carbink", "Dunsparce", "Poltchageist", "Sinistea", "Carbink"),
            Pregunta("¿Cuál de estos pokemon ha ganado más mundiales en VGC Masters Division?", "VGC", "Medio", "Cresselia", "Kyogre", "Heatran", "Urshifu", "Cresselia"),
            Pregunta("¿De qué tipo es Mega Kangaskhan?", "Tabla de Tipos", "Medio", "Normal", "Lucha", "Normal/Acero", "Normal/Lucha", "Normal"),
            //Facil
            Pregunta("En los juegos de la serie principal, ¿cuál es el único movimiento que puede cambiar el tipo de un Pokémon de forma permanente durante el combate hasta que salga del campo?", "Tipos", "Facil", "Camuflaje (Camouflage)", "Rayo Burbuja (Bubble Beam)", "Rastro Ígneo (Burning Jealousy)", "Conversión (Conversion)", "Conversión (Conversion)"),
            Pregunta("¿Cuál de los siguientes Pokémon ha tenido un cambio de tipo oficial entre generaciones, alterando su combinación de tipos sin requerir forma regional ni megaevolución?", "Evoluciones", "Facil", "Charizard", "Gyarados", "Magnemite", "Clefairy", "Magnemite"),
            Pregunta("En la historia de los juegos de la serie principal, ¿cuál fue el primer Pokémon legendario disponible mediante un evento distribuido exclusivamente fuera del juego base?", "Eventos", "Facil", "Celebi", "Jirachi", "Mew", "Deoxys", "Celebi"),
            Pregunta("En términos de jugabilidad competitiva en generaciones tempranas, ¿por qué Snorlax se consideraba una amenaza tan grande en el formato de combates individuales (singles), especialmente en la segunda generación?", "Competitivo", "Facil", "Porque podía megaevolucionar", "Por su combinación de enorme PS y ataque físico, junto con acceso a movimientos de recuperación y potenciación", "Por su velocidad extraordinariamente alta", "Porque era de tipo normal/fantasma", "Por su combinación de enorme PS y ataque físico, junto con acceso a movimientos de recuperación y potenciación"),
            Pregunta("En la región de Hoenn, ¿qué característica hacía especialmente único al sistema de concursos Pokémon en comparación con las mecánicas estándar de combate?", "Concursos", "Facil", "Los concursos sustituían permanentemente los movimientos", "Los concursos se basaban en las categorías de carisma, belleza, dureza, ingenio y dulzura, y en cómo los movimientos afectaban al público y a los jueces", "Los concursos utilizaban estadísticas ocultas de tipo combate", "En los concursos solo podía participar un Pokémon legendario", "Los concursos se basaban en las categorías de carisma, belleza, dureza, ingenio y dulzura, y en cómo los movimientos afectaban al público y a los jueces"),
            Pregunta("En la cuarta generación, en la región de Sinnoh, ¿qué particularidad tenía el encuentro con Spiritomb que lo hacía especialmente difícil de obtener sin guía externa?", "Sinnoh", "Facil", "Exigía interactuar con otros 32 jugadores mediante la conexión inalámbrica subterránea antes de que apareciera", "Solo podía capturarse si el juego estaba conectado a un cartucho de la tercera generación", "Requería derrotar a la Liga Pokémon sin perder ningún combate", "Aparecía de forma aleatoria en la hierba alta", "Exigía interactuar con otros 32 jugadores mediante la conexión inalámbrica subterránea antes de que apareciera"),
            Pregunta("En la quinta generación (Blanco y Negro), ¿qué hacía especialmente destacable a la región de Teselia en términos de disponibilidad de Pokémon durante la historia principal?", "Teselia", "Facil", "Solo se podían capturar Pokémon de generaciones anteriores", "El juego forzaba al jugador a usar solo Pokémon iniciales", "Durante la historia principal, la Pokédex regional estaba compuesta casi exclusivamente por nuevos Pokémon de quinta generación", "Todos los legendarios de generaciones anteriores estaban disponibles", "Durante la historia principal, la Pokédex regional estaba compuesta casi exclusivamente por nuevos Pokémon de quinta generación"),
            Pregunta("En la sexta generación (X/Y), ¿qué innovación importante relacionada con las batallas se introdujo y cambió significativamente la dinámica de la velocidad y el uso de movimientos estratégicos?", "Mega", "Facil", "La eliminación completa de las prioridades de movimiento", "La introducción de batallas de 4 contra 4", "La posibilidad de cambiar de movimiento a mitad del turno", "La megaevolución, que se activaba al inicio del turno y afectaba inmediatamente a las estadísticas y habilidades", "La megaevolución, que se activaba al inicio del turno y afectaba inmediatamente a las estadísticas y habilidades"),
            Pregunta("En la séptima generación (Sol y Luna), ¿qué limitación importante tenían los movimientos Z respecto al uso repetido en combate?", "Z-Movimientos", "Facil", "Podían usarse una vez por cada Pokémon del equipo", "Solo podían usarse una vez por combate para todo el equipo", "Podían usarse un número ilimitado de veces", "Solo podían usarse si el rival tenía más PS", "Solo podían usarse una vez por combate para todo el equipo"),
            Pregunta("En la octava generación (Espada y Escudo), ¿qué aspecto de la mecánica Dinamax y Gigamax influyó especialmente en el formato competitivo VGC (dobles oficiales)?", "Dinamax", "Facil", "El aumento temporal de PS, junto con la transformación de los movimientos en movimientos Dinamax con efectos secundarios que podían alterar el clima, el terreno o las estadísticas del equipo", "La obligación de Dinamaxear siempre en el primer turno", "La prohibición total de objetos", "La posibilidad de Dinamax solo a Pokémon legendarios", "El aumento temporal de PS, junto con la transformación de los movimientos en movimientos Dinamax con efectos secundarios"),
            //Medio
            Pregunta("En los juegos de la serie principal, ¿cuál fue el primer Pokémon que se mostró jamás en televisión en el famoso glitch de la beta de Pokémon Rojo y Verde japonés, durante una demostración temprana del combate?", "Historia", "Medio", "Nidorino", "Rhydon", "Gengar", "Clefairy", "Gengar"),
            Pregunta("En las versiones originales japonesas de Pokémon Rojo y Verde, ¿qué peculiaridad tenía el tipo Fantasma frente al tipo Psíquico en la tabla de tipos?", "Tipos", "Medio", "Los movimientos Fantasma eran súper eficaces contra Psíquico", "Los movimientos Fantasma no afectaban a Psíquico", "Fantasma y Psíquico se dañaban mutuamente con efectividad normal", "Los movimientos Psíquico eran inmunes a todos los tipos excepto Fantasma", "Los movimientos Fantasma no afectaban a Psíquico"),
            Pregunta("En Pokémon Oro, Plata y Cristal, ¿qué condición específica se debía cumplir para poder enfrentarse a Red en el Monte Plateado?", "Johto", "Medio", "Haber capturado al menos 240 Pokémon en la Pokédex nacional", "Haber vencido a la Torre Batalla en nivel 50", "Completar todos los eventos con Suicune y obtener su entrada en la Pokédex", "Derrotar a todos los líderes de gimnasio de Johto y Kanto", "Derrotar a todos los líderes de gimnasio de Johto y Kanto"),
            Pregunta("En Pokémon Rubí, Zafiro y Esmeralda, ¿qué peculiaridad tenía el método original para obtener a Deoxys sin eventos oficiales ni intercambios, si solo se contaba con esos cartuchos de la tercera generación?", "Hoenn", "Medio", "Podías conseguirlo tras vencer 100 veces seguidas en la Torre Batalla", "Se obtenía completando la Pokédex de Hoenn al 100%", "Era imposible obtenerlo legítimamente en el juego sin eventos externos", "Aparecía de forma salvaje en una isla secreta accesible por un truco con el reloj interno", "Era imposible obtenerlo legítimamente en el juego sin eventos externos"),
            Pregunta("En Pokémon Diamante, Perla y Platino, ¿qué detalle específico hacía único al combate contra Cynthia respecto a otros Campeones anteriores?", "Sinnoh", "Medio", "Era la única Campeona cuyo nivel más alto superaba el nivel 80 en la historia principal", "Su equipo estaba equilibrado en muchos tipos y sin un tema mono-tipo claro", "Era el primer Campeón que usaba un legendario en su equipo principal", "Era la primera Campeona con un equipo completamente formado por Pokémon de tipo Dragón", "Su equipo estaba equilibrado en muchos tipos y sin un tema mono-tipo claro"),
            Pregunta("En Pokémon Blanco y Negro, ¿qué circunstancia especial podía hacer que el combate final de la Liga de Teselia fuera muy diferente al formato tradicional de enfrentar solo al Campeón?", "Teselia", "Medio", "El combate final se convertía en un multibattle junto a tu rival contra el Campeón", "N aparecía con el castillo emergiendo y reemplazaba al combate contra el Campeón", "El Campeón cambiaba cada vez según tu ID de entrenador", "Podías saltarte a la Elite Four si habías ganado el Frente Batalla antes", "N aparecía con el castillo emergiendo y reemplazaba al combate contra el Campeón"),
            Pregunta("En Pokémon X y Y, ¿qué característica del Pokémon Floette de AZ lo hacía imposible de obtener por métodos normales de juego, a pesar de estar programado en los datos internos?", "Mega", "Medio", "Solo podía evolucionar a un nuevo Pokémon legendario bloqueado por región", "Tenía un tipo adicional escondido que no se mostraba en pantalla", "Su valor de amistad estaba fijado al máximo y no podía modificarse", "Poseía un movimiento exclusivo llamado Light of Ruin y una forma única sin evento de distribución", "Poseía un movimiento exclusivo llamado Light of Ruin y una forma única sin evento de distribución"),
            Pregunta("En Pokémon Sol y Luna, ¿qué mecánica concreta se introdujo en los combates contra líderes de prueba (Kahuna y Pokémon dominantes) que afectaba de forma importante al ritmo estratégico respecto a los gimnasios clásicos?", "Alola", "Medio", "Los combates tenían siempre límite de turnos", "Cada Kahuna usaba dos Mega Evoluciones en el mismo combate", "Los Pokémon dominantes podían llamar aliados de forma repetida durante el combate", "Las pruebas obligaban a utilizar exclusivamente Pokémon nativos de Alola", "Los Pokémon dominantes podían llamar aliados de forma repetida durante el combate"),
            Pregunta("En Pokémon Espada y Escudo, al enfrentarte al líder de gimnasio de tipo Fantasma o de tipo Lucha (según la versión), ¿qué elemento de diseño hacía estos gimnasios especialmente recordados en términos de ambientación y mecánica interna?", "Gimnasios", "Medio", "Un sistema de puzles de rotación de salas basado en relojes de arena", "Un laberinto tridimensional con cambio de gravedad", "La necesidad de resolver acertijos escritos con lenguaje antiguo dentro del gimnasio", "Una mecánica de combates encadenados con puntuación de público y efectos de cámara tipo programa de televisión", "Una mecánica de combates encadenados con puntuación de público y efectos de cámara tipo programa de televisión"),
            Pregunta("En Pokémon Escarlata y Púrpura, ¿qué rasgo de diseño del Área Cero refuerza la idea de que es un lugar central para la historia, más allá de ser simplemente una zona de alto nivel con Pokémon raros?", "Paldea", "Medio", "La imposibilidad total de usar objetos dentro del Área Cero", "La presencia de un descenso en espiral con múltiples niveles y diálogos continuos entre los acompañantes", "Un sistema de combates automáticos sin intervención del jugador", "El bloqueo del uso de la función de guardado mientras se está dentro", "La presencia de un descenso en espiral con múltiples niveles y diálogos continuos entre los acompañantes"),
            //Dificil
            Pregunta("En los juegos principales, ¿qué condición específica debe cumplirse para que se active la forma completa de Zygarde (Zygarde Complete Forme) durante una batalla?", "Zygarde", "Dificil", "Que Zygarde use un movimiento de tipo Dragón al inicio del turno", "Que los PS de Zygarde bajen a la mitad o menos por primera vez en la batalla", "Que Zygarde derrote al menos a un Pokémon enemigo en esa batalla", "Que el entrenador use una Célula Zygarde desde la mochila durante el combate", "Que los PS de Zygarde bajen a la mitad o menos por primera vez en la batalla"),
            Pregunta("En Pokémon Oro, Plata y Cristal (segunda generación), ¿qué peculiaridad tiene el combate contra Red en la cima del Monte Plateado respecto a sus Pokémon y el entorno que lo diferencia de la mayoría de combates finales?", "Johto", "Dificil", "Todos sus Pokémon tienen IV perfectos y naturaleza fija competitiva", "Los niveles de sus Pokémon superan el nivel de la Liga y no hay música de victoria normal al derrotarlo", "La batalla se desarrolla bajo una tormenta de granizo permanente que no puede cambiarse", "Su Pikachu es el único Pikachu del juego con un movimiento exclusivo por evento", "Los niveles de sus Pokémon superan el nivel de la Liga y no hay música de victoria normal al derrotarlo"),
            Pregunta("En la saga principal, ¿cuál de las siguientes afirmaciones sobre el método original para obtener a Mew de forma legítima sin eventos externos en Pokémon Rojo y Verde japoneses es correcta?", "Mew", "Dificil", "Se desbloqueaba a Mew derrotando 100 veces seguidas a la Liga Pokémon sin perder ninguna batalla", "En cartuchos japoneses tempranos, empleados de la compañía podían escribir a Mew en las partidas usando una máquina especial en tiendas", "Se desbloqueaba a Mew derrotando 100 veces seguidas a la Liga Pokémon sin perder ninguna batalla", "En cartuchos japoneses tempranos, empleados de la compañía podían escribir a Mew en las partidas usando una máquina especial en tiendas", "En cartuchos japoneses tempranos, empleados de la compañía podían escribir a Mew en las partidas usando una máquina especial en tiendas"),
            Pregunta("En Pokémon Esmeralda, al desafiar la Torre Batalla (Battle Tower), ¿qué característica del sistema de selección de oponentes la hace notoriamente diferente y más impredecible que en Rubí y Zafiro?", "Hoenn", "Dificil", "Cada planta de la torre tiene un tipo de Pokémon exclusivo, como en los gimnasios", "La IA puede cambiar de Pokémon leyendo directamente los inputs del jugador en tiempo real", "Existe un gran pool de entrenadores y equipos predefinidos, y se seleccionan combinaciones más variadas de forma pseudorrandómica", "Los equipos rivales se generan completamente al azar sin listas predefinidas", "Existe un gran pool de entrenadores y equipos predefinidos, y se seleccionan combinaciones más variadas de forma pseudorrandómica"),
            Pregunta("En Pokémon Negro 2 y Blanco 2, ¿qué detalle técnico hace especialmente singular la batalla contra el Pokémon Kyurem Blanco o Kyurem Negro en cuanto a su música y presentación?", "Teselia", "Dificil", "Incluye por primera vez en la saga una pista musical con coros humanos sampleados durante la batalla", "La música de batalla está dividida en varias capas que se mezclan de forma distinta según si luchas contra Kyurem Blanco o Negro", "Comparte el mismo tema musical que los líderes de gimnasio, pero en una tonalidad menor", "Es la única batalla donde la música cambia dinámicamente de tempo según los PS del jugador", "La música de batalla está dividida en varias capas que se mezclan de forma distinta según si luchas contra Kyurem Blanco o Negro"),
            Pregunta("En Pokémon Colosseum para Nintendo GameCube, ¿qué limitación importante hace que la captura de Pokémon sea más desafiante en comparación con los juegos principales de la misma generación?", "Colosseum", "Dificil", "No existe la posibilidad de causar estados alterados como sueño o parálisis para aumentar la tasa de captura", "Solo puedes capturar Pokémon Oscuros pertenecientes a entrenadores, y nunca aparecen salvajes", "Las Poké Balls no tienen diferencias de índice de captura; todas funcionan como Poké Balls normales", "No se pueden usar objetos curativos durante los combates, solo Poké Balls", "Solo puedes capturar Pokémon Oscuros pertenecientes a entrenadores, y nunca aparecen salvajes"),
            Pregunta("En Pokémon X y Y, ¿qué peculiaridad tiene el sistema de apariciones de hordas (Horde Encounters) que lo vuelve especialmente útil para la caza de Pokémon variocolor (shiny hunting)?", "Shiny", "Dificil", "Las hordas siempre tienen al menos un Pokémon con 3 IV perfectos como mínimo", "Multiplica la probabilidad de encontrar un variocolor en un turno al presentar 5 Pokémon a la vez en un solo encuentro", "Cada horda contiene exactamente un Pokémon con naturaleza fija aleatoria que no se puede cambiar", "Permite que el jugador fuerce una horda de 5 Pokémon iniciales al usar un objeto raro de la Boutique", "Multiplica la probabilidad de encontrar un variocolor en un turno al presentar 5 Pokémon a la vez en un solo encuentro"),
            Pregunta("En Pokémon Sol y Luna, ¿qué detalle sobre el movimiento Z de tipo Normal exclusivo de Snorlax, Pulverizing Pancake, lo distingue en términos de requisitos previos para usarlo?", "Z-Movimientos", "Dificil", "Exige que Snorlax tenga la habilidad Oculta y una amistad máxima con el entrenador", "Solo puede ejecutarse si Snorlax ha usado previamente el movimiento Descanso en esa misma batalla", "Solo se puede usar una vez por partida completa, no solo una vez por combate", "Requiere que Snorlax conozca Giga Impacto y lleve equipado el Z-Crystal específico, Snorlium Z", "Requiere que Snorlax conozca Giga Impacto y lleve equipado el Z-Crystal específico, Snorlium Z"),
            Pregunta("En Pokémon Leyendas: Arceus, ¿qué cambio clave en la mecánica de los combates altera profundamente la manera de planear turnos en comparación con los juegos tradicionales?", "Leyendas Arceus", "Dificil", "Los combates siempre son multijugador en línea, incluso en la historia principal", "Los tipos ya no tienen ventajas ni desventajas; todo daño se calcula como neutro", "Los Pokémon pueden ejecutar varias acciones seguidas si su velocidad relativa lo permite, gracias a los estilos Ágil y Fuerte", "Los movimientos ya no tienen PP y pueden usarse un número ilimitado de veces", "Los Pokémon pueden ejecutar varias acciones seguidas si su velocidad relativa lo permite, gracias a los estilos Ágil y Fuerte"),
            )
    }
}